#ifndef AREAL_SRC_VERSION_H_
#define AREAL_SRC_VERSION_H_

#define AREAL_VERSION_MAJOR 0
#define AREAL_VERSION_MINOR 1
#define AREAL_VERSION_MICRO 0
#define AREAL_VERSION "0.1.0"

#endif  // AREAL_SRC_VERSION_H_
